version: 1.0.{build}
image: Visual Studio 2022
environment:
  matrix:
  - PYTHON: Python39-x64
  - PYTHON: Python310-x64
  - PYTHON: Python311-x64
  - PYTHON: Python312-x64
  - PYTHON: Python313-x64
build_script:
- ps: >-
    $env:Path += ";C:\${Env:PYTHON}\Scripts"
    & "C:\${Env:PYTHON}\python.exe" -m pip install -e .
test_script:
- ps: >-
    & "C:\${Env:PYTHON}\python.exe" tests.py -v
