version: 1.0.{build}
image: Visual Studio 2022
environment:
  matrix:
  - PYTHON: Python313-x64
build_script:
- ps: >-
    $env:Path += ";C:\${Env:PYTHON}\Scripts"
    & "C:\${Env:PYTHON}\python.exe" -m pip install -e .[develop]
test_script:
- ps: >-
    $env:Path += ";C:\${Env:PYTHON}\Scripts"
    # use pytest because appveyor triggers error when anything goes to stderr
    & pytest.exe tests.py -v --junitxml=results.xml
