environment:
    matrix:
        - PYTHON: Python35
        - PYTHON: Python36
        - PYTHON: Python37

install:
    - C:\%PYTHON%\python.exe -m pip install .

build: off

test_script:
    - C:\%PYTHON%\python.exe tests.py
