# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019

environment:
  # https://devguide.python.org/versions
  matrix:
  - TOXENV: py38
  - TOXENV: py39
  - TOXENV: py310
  - TOXENV: py311

build: false

install:
  # - py --list
  # - py -m pip install --upgrade pip
  - py -m pip install -e .[test]

test_script:
  - py -m tox
