image: Visual Studio 2022

build: off

init:
  - echo "=== STARTING APPVEYOR BUILD ==="
  - python --version

install:
  - echo "=== INSTALLING ==="
  - python -m pip install -e .

test_script:
  - echo "=== TESTING ==="
  - python tests.py -v
