repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
        language_version: python
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        language: python
        additional_dependencies: [flake8-comprehensions]
        args: [--max-line-length=999]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
